### PR TITLE
Update to 23w44a

### PR DESCRIPTION
**Pull request by Leguan16**
This is my first attempt of updating mache.

I also updated parchment from 1.20.1 to 1.20.2 

The only complication was the [FixProjectileStoredItem](https://github.com/Leguan16/mache/blob/snap/23w44a/versions/23w44a/patches/net/minecraft/util/datafix/fixes/FixProjectileStoredItem.java.patch) patch where I had to remove the generic type of a method. 
I also had to rename some variables and convert a `char` variable to `String`.

Feedback is appreciated :)

### CODE REVIEW

**Comment by DenWav** [comment]
Taking a look at this, it looks like you did a good job. Since we are still spinning up our new tooling we aren't super active on this as we aren't using it directly yet. I don't know for sure how we'll handle PRs like this since our workflow requires it to target a new branch - maybe we can just create the branch and re-target the PR. We haven't worked that out yet.

I'll take a closer look at this and if everything checks out I'll merge it. We have later versions, but not this one, so might as well not let your work go to waste.

**Comment by DenWav** [comment]
I don't understand changing `PREFIX_CODE` from a `char` to a `String` - that doesn't look like a decompile fix. Can you explain that?

**Comment by Leguan16** [comment]
Hey, thanks for taking a look even though later versions exist.

I had to change it from `char` to `String` cause it threw this compiler error:
image

Maybe it's just a dumb moment from me but changing it to a `String` was the quick fix for me. Maybe you have an idea why it happened.

**Comment by 456dev** [comment]
i cloned your branch, and deleted the chat formating patch and it seemed to compile fine for me
character encoding quirk?

**Comment by Leguan16** [comment]
Did you just remove the patch or did you revert it to a `char` and try to compile?

**Comment by 456dev** [comment]
i think i removed the patch, did applyPatches and then gradle build
but ill check again, im doubting myself :)

**Comment by 456dev** [comment]
yeah 100% built ok

```
git clone git@github.com:Leguan16/mache.git
cd mache
git switch snap/23w44a 
cd versions/23w44a/patches/net/minecraft
rm ChatFormatting.java.patch
cd ../../../..
./gradlew :versions:23w44a:applyPatches
./gradlew :versions:23w44a:build
```

**Comment by Leguan16** [comment]
Very interesting

**Comment by MiniDigger** [comment]
Haven't tried but I had windows issues in the file before

**Comment by DenWav** [comment]
Yeah could be an encoding issue, I see you're on WSL too. I'll see if I can figure out what the issue is, likely needs to be fixed in the tooling layer.

**Comment by MiniDigger** [comment]
Not sure if it's worth spending time on it it's just manifesting in this one location and fixed by a simple patch

**Comment by Leguan16** [comment]
The `ChunkMap.java` patch also has the same change.

**Comment by DenWav** [comment]
@MiniDigger the purpose of mache is to be minimum necessary patches, it shouldn't change the code in that way. It's worth fixing to maintain the correctness guarantee that mache wants to support.

**Comment by MiniDigger** [comment]
finally looked at the diff here in detail, what I was refering to was me doing this https://github.com/PaperMC/mache/blob/snap/23w35a/versions/23w35a/patches/net/minecraft/ChatFormatting.java.patch because it caused compiler issues before, but either an java update fixed it or something in our tooling changed because we dropped the patch and it still works fine for me 🤷 
I agree that the two diffs here in this PR should be dropped too

**Comment by Leguan16** [comment]
Yep I agree. I mainly did that to get it compiling. Would be nice if we can figure out what's the actual issue here. I hope I get to take a look on this on the weekend. Thanks for the input!

**Comment by Leguan16** [comment]
as I expected defining the encoding in the build file fixed the issue. 
```gradle
tasks {
    compileJava {
        options.encoding = "UTF-8"
    }
}
```

I currently put the piece of code above somewhere in mache.kts. If there is a better place let me know and I will change it. Or send me a patch and I'll apply it.

**Pull request closed without merging**
